var express = require('express');
var router = express.Router();

var conn = require('../mysql/cake');

var cake = [
    {
      cakeid:1,
      name:'我想要的幸福',
      price:188,
      oldprice:226, 
      material:'圆形欧式水果蛋糕，各色时令水果方格式艺术装饰，纯手工巧克力片围边。',
      word:'我想要的幸福，都只是一天天平淡日子里的执手相看；只是相处时温暖的关怀；只是在那一天，我们走进婚姻时的美丽瞬间。',
      introduce:'九宫格水果蛋糕',
      url:'https://www.dangao.com/proimgs/711673175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-711673minfo2.jpg',
      lun2:'https://www.dangao.com/proimgs/C-711673minfo1.jpg',
      lun3:'https://www.dangao.com/proimgs/C-711673minfo3.jpg',
      img1:'https://www.dangao.com/proimgs/C-711673mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-711673mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-711673mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-711673mdesC2.jpg',
      img5:'https://www.dangao.com/proimgs/C-711673mdesC3.jpg',
      img6:'https://www.dangao.com/proimgs/C-711673mdesC4.jpg',
      ishot:'true',
      number:1
    },
    {
      cakeid:2,
      name:'梦幻芭比',
      price:198,
      oldprice:238, 
      material:'新鲜奶油、戚风水果夹层蛋糕胚（芭比随机搭配）',
      word:'讨好味觉的艺术展现的淋漓尽致，可爱的芭比，不是童话，胜似童话。',
      introduce:'可爱芭比鲜奶蛋糕',
      url:'https://www.dangao.com/proimgs/701716175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-701716minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-701716minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-701716minfo3.jpg',
      lun4:'https://www.dangao.com/proimgs/C-701716minfo4.jpg',
      lun5:'https://www.dangao.com/proimgs/C-701716minfo5.jpg',
      img1:'https://www.dangao.com/proimgs/C-701716mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-701716mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-701716mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-701716mdesC2.jpg',
      img5:'https://www.dangao.com/proimgs/C-701716mdesC3.jpg',
      img6:'https://www.dangao.com/proimgs/C-701716mdesC4.jpg',
      number:1
    },
    {
      cakeid:3,
      name:'一生的爱',
      price:188,
      oldprice:226, 
      material:'圆形巧克力蛋糕，巧克力色奶油花装饰，水果片点缀',
      word:'我想要的幸福，都只是一天天平淡日子里的执手相看；只是相处时温暖的关怀；只是在那一天，我们走进婚姻时的美丽瞬间。',
      introduce:'浓情巧克力诱惑',
      url:'https://www.dangao.com/proimgs/708039175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-708039minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-708039minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-708039minfo3.jpg',
      lun4:'https://www.dangao.com/proimgs/C-708039minfo4.jpg',
      lun5:'https://www.dangao.com/proimgs/C-708039minfo5.jpg',
      img1:'https://www.dangao.com/proimgs/C-708039mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-708039mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-708039mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-708039mdesC2.jpg',
      img5:'https://www.dangao.com/proimgs/C-708039mdesC3.jpg',
      img6:'https://www.dangao.com/proimgs/C-708039mdesC4.jpg',
      number:1
    },
    {
      cakeid:4,
      name:'愿得一人心',
      price:198,
      oldprice:218, 
      material:'新鲜奶油，时令水果，鸡蛋牛奶水果夹层胚',
      word:'一生只为你心动回旋，真爱永不止息',
      introduce:'满满的水果和爱心',
      url:'https://www.dangao.com/proimgs/721018175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-721018minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-721018minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-721018minfo3.jpg',
      lun4:'https://www.dangao.com/proimgs/C-721018minfo4.jpg',
      img1:'https://www.dangao.com/proimgs/C-721018mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-721018mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-721018mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-721018mdesC2.jpg',
      img5:'https://www.dangao.com/proimgs/C-721018mdesC3.jpg',
      number:1
    },
    {
      cakeid:5,
      name:'巨蟹座专属蛋糕',
      price:198,
      oldprice:238, 
      material:'新鲜奶油搭配时令水果',
      word:'蟹蟹有你',
      introduce:'爱家爱生活的巨蟹座',
      url:'https://www.dangao.com/proimgs/711002175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-711002minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-711002minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-711002minfo3.jpg',
      lun4:'https://www.dangao.com/proimgs/C-711002minfo4.jpg',
      img1:'https://www.dangao.com/proimgs/C-711002mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-711002mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-711002mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-711002mdesC2.jpg',
      number:1
    },
    {
      cakeid:6,
      name:'想念',
      price:188,
      oldprice:208, 
      material:'圆形水果蛋糕，水果铺面，白色巧克力围边',
      word:'忘了时间，忘了诺言，忘不了对你的想念；忘了工作，忘了睡眠，忘不了对你的祝福，愿你开心快乐，万事顺利！',
      introduce:'夏日的一抹清凉',
      url:'https://www.dangao.com/proimgs/711687175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-711687minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-711687minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-711687minfo3.jpg',
      img1:'https://www.dangao.com/proimgs/C-711687mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-711687mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-711687mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-711687mdesC2.jpg',
      img5:'https://www.dangao.com/proimgs/C-711687mdesC3.jpg',
      number:1
    },
    {
      cakeid:7,
      name:'微微一笑',
      price:188,
      oldprice:208, 
      material:'新鲜奶油，绵密的新鲜当季的时令水果',
      pack:'果酱装饰',
      word:'不约同哼唱同一段曲调，你嘴角微笑，这感觉很奇妙',
      introduce:'微微一笑很倾城',
      url:'https://www.dangao.com/proimgs/712001175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-712001minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-712001minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-712001minfo3.jpg',
      img1:'https://www.dangao.com/proimgs/C-712001mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-712001mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-712001mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-712001mdesC2.jpg',
      img5:'https://www.dangao.com/proimgs/C-712001mdesC3.jpg',
      img6:'https://www.dangao.com/proimgs/C-712001mdesC4.jpg',
      number:1
    },
    {
      cakeid:8,
      name:'生日快乐',
      price:188,
      oldprice:226, 
      material:'圆形欧式水果蛋糕，拇指饼干围边',
      word:'好多年了，每一个生日我们都没忘记给对方祝福，希望这一生都拥有这友情，真心祝你生日快乐！',
      introduce:'祝你生日快乐',
      url:'https://www.dangao.com/proimgs/711701175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-711701minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-711701minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-711701minfo3.jpg',
      img1:'https://www.dangao.com/proimgs/C-711701mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-711701mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-711701mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-711701mdesC2.jpg',
      img5:'https://www.dangao.com/proimgs/C-711701mdesC3.jpg',
      ishot:'true',
      number:1
    },
    {
      cakeid:9,
      name:'福禄寿来',
      price:198,
      oldprice:218, 
      material:'新鲜奶油搭配时令水果',
      word:'福禄寿来喜满堂，添光添彩添吉祥',
      introduce:'福禄寿来喜满堂',
      url:'https://www.dangao.com/proimgs/711002175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-711004minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-711004minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-711004minfo3.jpg',
      lun4:'https://www.dangao.com/proimgs/C-711004minfo4.jpg',
      img1:'https://www.dangao.com/proimgs/C-711004mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-711004mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-711004mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-711004mdesC2.jpg',
      number:1
    },
    {
      cakeid:10,
      name:'玫瑰色恋人',
      price:198,
      oldprice:238, 
      material:'新鲜时令水果搭配玫瑰花装饰，甜蜜而又浪漫',
      word:'有我陪伴，多苦都变成甜',
      introduce:'玫瑰与鲜奶的完美融合',
      url:'https://www.dangao.com/proimgs/701731175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-701731minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-701731minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-701731minfo3.jpg',
      img1:'https://www.dangao.com/proimgs/C-701731mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-701731mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-701731mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-701731mdesC2.jpg',
      number:1
    },
    {
      cakeid:11,
      name:'环游世界的梦想',
      price:298,
      oldprice:318, 
      material:'法拉利小汽车造型，芭比娃娃，新鲜奶油',
      word:'有我陪伴，多苦都变成甜',
      introduce:'好朋友一辈子一起走',
      url:'https://www.dangao.com/proimgs/066219175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-066219minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-066219minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-066219minfo3.jpg',
      img1:'https://www.dangao.com/proimgs/C-066219mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-066219mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-066219mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-066219mdesC2.jpg',
      number:1
    },
    {
      cakeid:12,
      name:'甜心芭比',
      price:198,
      oldprice:218, 
      material:'新鲜奶油搭配时令水果',
      word:'还记得小时候最初的梦想吗，谁还不是个小公主来着',
      introduce:'可爱芭比水果蛋糕',
      url:'https://www.dangao.com/proimgs/711003175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-711003minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-711003minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-711003minfo3.jpg',
      lun4:'https://www.dangao.com/proimgs/C-711003minfo4.jpg',
      img1:'https://www.dangao.com/proimgs/C-711003mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-711003mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-711003mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-711003mdesC2.jpg',
      number:1
    },
    {
      cakeid:13,
      name:'熊二',
      price:186,
      oldprice:206, 
      material:'圆形水果艺术蛋糕，《熊出没》中熊二造型，水果围边',
      word:'熊大，熊大！光头强又在砍俺们的树了！俺的蜂蜜，俺的坚果，俺的小蝴蝶！',
      introduce:'谁动了我的蜂蜜？',
      url:'https://www.dangao.com/proimgs/711686175228.jpg',
      lun1:'https://www.dangao.com/imgpro/7116864201.jpg',
      img1:'https://www.dangao.com/proimgs/C-711686mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-711686mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-711686mdesC1.jpg',
      number:1
    },
    {
      cakeid:14,
      name:'快乐星球',
      price:188,
      oldprice:226, 
      material:'多种时令水果，新鲜奶油 ',
      pack:'鸡蛋 牛奶水果夹层胚',
      word:'无论在外有多少烦恼的事情，只要看你天真无邪的笑容，就是最大的快乐！',
      introduce:'感受你成长的快乐',
      url:'https://www.dangao.com/proimgs/721032175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-721032minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-721032minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-721032minfo3.jpg',
      img1:'https://www.dangao.com/proimgs/C-721032mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-721032mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-721032mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-721032mdesC2.jpg',
      img5:'https://www.dangao.com/proimgs/C-721032mdesC3.jpg',
      number:1
    },
    {
      cakeid:15,
      name:'七彩果园',
      price:198,
      oldprice:238, 
      material:'方形水果蛋糕，新鲜奶油、果肉铺面，水果夹层蛋糕胚。',
      word:'欢乐的时光想要与你分享，祝你天天开心我的宝贝！',
      introduce:'七彩水果大作战',
      url:'https://www.dangao.com/proimgs/701709175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-701709minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-701709minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-701709minfo1.jpg',
      lun4:'https://www.dangao.com/proimgs/C-701709minfo2.jpg',
      img1:'https://www.dangao.com/proimgs/C-701709mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-701709mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-701709mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-701709mdesC2.jpg',
      ishot:'true',
      number:1
    },
    {
      cakeid:16,
      name:'布达佩斯之恋',
      price:168,
      oldprice:188, 
      material:'圆形奶油蛋糕，选用新鲜奶油，原味戚风蛋糕胚',
      word:'最幸福的事情就是在我最美的时刻遇见了你。',
      introduce:'甜蜜在味觉中蔓延',
      url:'https://www.dangao.com/proimgs/701715175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-701715minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-701715minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-701715minfo3.jpg',
      lun4:'https://www.dangao.com/proimgs/C-701715minfo4.jpg',
      lun5:'https://www.dangao.com/proimgs/C-701715minfo5.jpg',
      img1:'https://www.dangao.com/proimgs/C-701715mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-701715mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-701715mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-701715mdesC2.jpg',
      iste:'true',
      number:1
    },
    {
      cakeid:17,
      name:'明明白白我的心',
      price:198,
      oldprice:218, 
      material:'时令水果，新鲜奶油，外围玫瑰花瓣',
      pack:'鸡蛋牛奶胚',
      word:'甜蜜梦幻的浪漫气息，品尝时仿佛在享受一场美好的爱情',
      introduce:'心形玫瑰花水果蛋糕',
      url:'https://www.dangao.com/proimgs/721030175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-721030minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-721030minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-721030minfo3.jpg',
      lun4:'https://www.dangao.com/proimgs/C-721030minfo4.jpg',
      img1:'https://www.dangao.com/proimgs/C-721030mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-721030mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-721030mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-721030mdesC2.jpg',
      img5:'https://www.dangao.com/proimgs/C-721030mdesC3.jpg',
      number:1
    },
    {
      cakeid:18,
      name:'缤纷盛果',
      price:188,
      oldprice:246, 
      material:'圆形欧式水果蛋糕，各色水果饱满装饰，纯手工巧克力片围边。',
      word:'特别的爱给特别的你，愿我的祝福像阳光一样环绕着你，真诚的祝愿健康和快乐永远伴随你，生日快乐',
      introduce:'水果遇到手工巧克力',
      url:'https://www.dangao.com/proimgs/711667175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-711667minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-711667minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-711667minfo3.jpg',
      lun4:'https://www.dangao.com/proimgs/C-711667minfo4.jpg',
      lun5:'https://www.dangao.com/proimgs/C-711667minfo5.jpg',
      img1:'https://www.dangao.com/proimgs/C-711667mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-711667mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-711667mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-711667mdesC2.jpg',
      img5:'https://www.dangao.com/proimgs/C-711667mdesC3.jpg',
      isnew:'true',
      number:1
    },
    {
      cakeid:19,
      name:'女神小七',
      price:228,
      oldprice:248, 
      material:'新鲜玫瑰花，抹茶粉铺面搭配细腻丝滑的新鲜奶油',
      pack:'巧克力屑点缀',
      word:'如果有一个人，有一扇门，不论你何时到来都热情欢迎，这个城市或许就不再那么陌生。',
      introduce:'最懂女神心的小七',
      url:'https://www.dangao.com/proimgs/721006175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-721006minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-721006minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-721006minfo3.jpg',
      img1:'https://www.dangao.com/proimgs/C-721006mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-721006mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-721006mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-721006mdesC2.jpg',
      number:1
    },
    {
      cakeid:20,
      name:'玫瑰之约',
      price:198,
      oldprice:218, 
      material:'新鲜奶油，鸡蛋牛奶胚，玫瑰花瓣围边',
      word:'终于让我遇见你，才懂的相逢相知的珍贵',
      introduce:'有玫瑰就有约会',
      url:'https://www.dangao.com/proimgs/721053175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-721053minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-721053minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-721053minfo3.jpg',
      lun4:'https://www.dangao.com/proimgs/C-721053minfo4.jpg',
      img1:'https://www.dangao.com/proimgs/C-721053mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-721053mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-721053mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-721053mdesC2.jpg',
      number:1
    },
    {
      cakeid:21,
      name:'Hello女神',
      price:236,
      oldprice:256, 
      material:'时尚花束7枝精品白玫瑰，4枝粉玫瑰',
      pack:'情人草、满天星间插、栀子叶、相思梅点缀',
      word:'你鲁莽的闯入我的世界，不吭一声，但我从未怀疑你就是我的女神',
      introduce:'女神最爱的小清新',
      url:'https://www.dangao.com/proimgs/011197175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-011197minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-011197minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-011197minfo3.jpg',
      img1:'https://www.dangao.com/proimgs/C-011197mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-011197mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-011197mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-011197mdesC2.jpg',
      img5:'https://www.dangao.com/proimgs/C-011197mdesC3.jpg',
      number:1
    },
    {
      cakeid:22,
      name:'宝贝，生日快乐',
      price:198,
      oldprice:218, 
      material:'11枝精品红玫瑰',
      pack:'满天星，黄莺丰满',
      word:'今天是你的生日，为你准备了生日礼物，希望你永远健康快乐！',
      introduce:'生日也需要鲜花',
      url:'https://www.dangao.com/proimgs/011169175228.jpg',
      lun1:'https://www.dangao.com/imgpro/0111694201.jpg',
      img1:'https://www.dangao.com/proimgs/C-011169mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-011169mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-011169mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-011169mdesC2.jpg',
      number:1
    },
    {
      cakeid:23,
      name:'浪漫密语',
      price:238,
      oldprice:258, 
      material:'11枝红玫瑰+尤加利叶点缀',
      pack:'尤加利叶',
      word:'对你的思念是一种无法用语言表达的温馨。',
      introduce:'11枝精品红玫瑰',
      url:'https://www.dangao.com/proimgs/011201175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-011201minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-011201minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-011201minfo3.jpg',
      lun4:'https://www.dangao.com/proimgs/C-011201minfo4.jpg',
      img1:'https://www.dangao.com/proimgs/C-011201mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-011201mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-011201mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-011201mdesC2.jpg',
      number:1
    },
    {
      cakeid:24,
      name:'守护爱情',
      price:338,
      oldprice:258, 
      material:'19枝红玫瑰',
      word:'爱是一个眼神，在不经意的一刻，悄无声息，不多言语，浪漫早已在心底交汇。',
      introduce:'19枝精品红玫瑰',
      url:'https://www.dangao.com/proimgs/019116175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-019116minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-019116minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-019116minfo3.jpg',
      img1:'https://www.dangao.com/proimgs/C-019116mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-019116mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-019116mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-019116mdesC2.jpg',
      number:1
    },
    {
      cakeid:25,
      name:'花样幸福',
      price:368,
      oldprice:388, 
      material:'6枝粉玫瑰，1枝多头香水百合，搭配欧式水果蛋糕',
      pack:'5枝白色雏菊，5枝绿色雏菊',
      word:'花样年华，演绎花样幸福',
      introduce:'鲜花蛋糕组合',
      url:'https://www.dangao.com/proimgs/500337175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-500337minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-500337minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-500337minfo3.jpg',
      lun4:'https://www.dangao.com/proimgs/C-500337minfo4.jpg',
      lun5:'https://www.dangao.com/proimgs/C-500337minfo5.jpg',
      img1:'https://www.dangao.com/proimgs/C-500337mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-500337mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-500337mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-500337mdesC2.jpg',
      number:1
    },
    {
      cakeid:26,
      name:'浪漫情人节',
      price:468,
      oldprice:488, 
      material:'19枝精品玫瑰，浪漫设计心心相印水果蛋糕',
      word:'和你在一起的每一天都是情人节',
      introduce:'鲜花蛋糕组合',
      url:'https://www.dangao.com/proimgs/500338175228.jpg',
      lun1:'https://www.dangao.com/proimgs/C-500338minfo1.jpg',
      lun2:'https://www.dangao.com/proimgs/C-500338minfo2.jpg',
      lun3:'https://www.dangao.com/proimgs/C-500338minfo3.jpg',
      lun4:'https://www.dangao.com/proimgs/C-500338minfo4.jpg',
      img1:'https://www.dangao.com/proimgs/C-500338mdesA1.jpg',
      img2:'https://www.dangao.com/proimgs/C-500338mdesB1.jpg',
      img3:'https://www.dangao.com/proimgs/C-500338mdesC1.jpg',
      img4:'https://www.dangao.com/proimgs/C-500338mdesC2.jpg',
      img5:'https://www.dangao.com/proimgs/C-500338mdesC3.jpg',
      number:1
    },
    {
      cakeid:27,
      name:'挚爱唯一',
      price:798,
      oldprice:818, 
      material:'三层圆形鲜奶蛋糕，白色鲜奶百合花装饰',
      word:'永结同心，百年好合！新婚愉快，甜甜蜜蜜',
      mark:'三层蛋糕，上下两层的尺寸相差最少4英寸。如:8寸至少叠12寸，而不能叠10寸。价格按上述价格各层的价格之和计算，标价按照中间层的尺寸。',
      introduce:'三层圆形鲜奶蛋糕',
      url:'https://www.dangao.com/proimgs/709001175228.jpg',
      lun1:'https://www.dangao.com/imgpro/7090014201.jpg',
      img2:'https://www.dangao.com/imgpro/7090014201.jpg',
      number:1
    },
    {
      cakeid:28,
      name:'爱的见证',
      price:1688,
      oldprice:1708, 
      material:'三层方形鲜奶蛋糕，白色雕花，鲜奶百合花',
      pack:'情侣,祝福,婚礼,庆典,生子,',
      word:'你们本就是天生一对，地造一双，而今共偕连理，今后更需彼此宽容、互相照顾，祝福你们!',
      mark:'三层蛋糕，上下两层的尺寸相差最少4英寸。如:8寸至少叠12寸，而不能叠10寸。价格按上述价格各层的价格之和计算，标价按照中间层的尺寸。',
      introduce:'三层方形鲜奶蛋糕',
      url:'https://www.dangao.com/proimgs/709002175228.jpg',
      lun1:'https://www.dangao.com/imgpro/7090024201.jpg',
      img2:'https://www.dangao.com/imgpro/7090024201.jpg',
      number:1
    },
    {
      cakeid:29,
      name:'快乐年华',
      price:898,
      oldprice:918, 
      material:'三层圆形鲜奶蛋糕，粉色鲜奶玫瑰花',
      word:'愿快乐的歌声永远伴你们同行，永浴于无穷的快乐年华。',
      mark:'三层带支架蛋糕，上下两层的尺寸相差最少2英寸。如:8寸至少叠10寸，价格按上述价格各层的价格之和计算，标价按照中间层的尺寸。' ,
      introduce:'三层圆形鲜奶蛋糕',
      url:'https://www.dangao.com/proimgs/709006175228.jpg',
      lun1:'https://www.dangao.com/imgpro/7090064201.jpg',
      img2:'https://www.dangao.com/imgpro/7090064201.jpg',
      number:1
    },
    {
      cakeid:30,
      name:'幸福到永远',
      price:918,
      oldprice:938, 
      material:'三层圆形鲜奶蛋糕，粉色鲜奶玫瑰花装饰',
      pack:'恋情,生日,祝福,婚庆,生子,',
      word:'愿爱洋溢在你甜蜜的生活中，让以后的每一个日子，都象今日这般辉煌喜悦！',
      mark:'三层带支架蛋糕，上下两层的尺寸相差最少2英寸。如:8寸至少叠10寸，价格按上述价格各层的价格之和计算，标价按照中间层的尺寸。' ,
      introduce:'三层心形鲜奶蛋糕',
      url:'https://www.dangao.com/proimgs/709007175228.jpg',
      lun1:'https://www.dangao.com/imgpro/7090074201.jpg',
      img2:'https://www.dangao.com/imgpro/7090074201.jpg',
      number:1
    },
    {
      cakeid:31,
      name:'未来',
      price:898,
      oldprice:918, 
      material:'三层圆形鲜奶蛋糕，奶油花装饰',
      pack:'恋情,生日,祝福,婚庆,生子,',
      word:'伸出爱的手，接往盈盈的祝福，让幸福绽放灿烂的花朵，迎向你们未来的日子...',
      mark:'三层带支架蛋糕，上下两层的尺寸相差最少2英寸。如:8寸至少叠10寸，价格按上述价格各层的价格之和计算，标价按照中间层的尺寸。' ,
      introduce:'三层圆形鲜奶婚礼蛋糕',
      url:'https://www.dangao.com/proimgs/709008175228.jpg',
      lun1:'https://www.dangao.com/imgpro/7090084201.jpg',
      img2:'https://www.dangao.com/imgpro/7090084201.jpg',
      number:1
    },
    {
      cakeid:32,
      name:'浪漫婚礼',
      price:1988,
      oldprice:2008, 
      material:'四层圆形鲜奶蛋糕，奶油花装饰',
      pack:'恋情,生日,祝福,婚庆',
      word:'他是词，你是谱，你俩就是一首和谐的歌。',
      mark:'三层带支架蛋糕，上下两层的尺寸相差最少2英寸。如:8寸至少叠10寸，价格按上述价格各层的价格之和计算，标价按照中间层的尺寸。' ,
      introduce:'四层圆形鲜奶蛋糕',
      url:'https://www.dangao.com/proimgs/709009175228.jpg',
      lun1:'https://www.dangao.com/imgpro/7090094201.jpg',
      img2:'https://www.dangao.com/imgpro/7090094201.jpg',
      number:1
    },
    {
      cakeid:33,
      name:'爱之旅',
      price:1188,
      oldprice:1208, 
      material:'四层鲜奶水果蛋糕，鲜奶太阳花装饰',
      pack:'恋情,生日,祝福,开业,生子,',
      word:'这时刻，是花开的时，是飞彩的时刻，是吉庆的时刻，是你大喜的时刻。天赐良缘，百年好合。',
      mark:'四层带支架蛋糕，上下两层的尺寸相差最少2英寸。如:8寸至少叠10寸，价格按上述价格各层的价格之和计算，标价按照第二层的尺寸。',
      introduce:'四层鲜奶水果蛋糕',
      url:'https://www.dangao.com/proimgs/709011175228.jpg',
      lun1:'https://www.dangao.com/imgpro/7090114201.jpg',
      img2:'https://www.dangao.com/imgpro/7090114201.jpg',
      number:1
    },
    {
      cakeid:34,
      name:'粉色天空',
      price:1988,
      oldprice:2008, 
      material:'五层鲜奶蛋糕，太阳花装饰',
      pack:'恋情,生日,祝福,婚庆,节日,',
      word:'祝你们永结同心，百年好合！新婚愉快，甜甜蜜蜜！',
      mark:'五层带支架蛋糕，上下两层的尺寸相差最少2英寸。如:8寸至少叠10寸，价格按上述价格各层的价格之和计算，标价按照中间层的尺寸。' ,
      introduce:'五层鲜奶蛋糕太阳花装',
      url:'https://www.dangao.com/proimgs/709012175228.jpg',
      lun1:'https://www.dangao.com/imgpro/7090124201.jpg',
      img2:'https://www.dangao.com/imgpro/7090124201.jpg',
    },
    {
      cakeid:35,
      name:'爱的殿堂',
      price:1706,
      oldprice:1726, 
      material:'五层心形鲜奶蛋糕，粉色鲜奶玫瑰花装饰',
      pack:'恋情,生日,祝福,婚庆,节日,',
      word:'伸出爱的手，接往盈盈的祝福，让幸福绽放灿烂的花朵，迎向你们未来的日子...祝新婚愉快。',
      mark:'五层带支架蛋糕，上下两层的尺寸相差最少2英寸。如:8寸至少叠10寸，价格按上述价格各层的价格之和计算，标价按照第二层的尺寸。',
      introduce:'五层心形鲜奶蛋糕',
      url:'https://www.dangao.com/proimgs/709013175228.jpg',
      lun1:'https://www.dangao.com/imgpro/7090134201.jpg',
      img2:'https://www.dangao.com/imgpro/7090134201.jpg',
    },
    {
      cakeid:36,
      name:'紫色年华',
      price:2388,
      oldprice:2408, 
      material:'六层鲜奶蛋糕，紫色鲜奶玫瑰花装饰',
      pack:'恋情,生日,祝福,婚庆,节日,',
      word:'清晨曙光初现，婚礼就在眼前；中午艳阳高照，微笑挂你唇间；傍晚日落西山，欢乐随你一天；婚后日日如此，幸福永驻身边。',
      mark:'六层带支架蛋糕，上下两层的尺寸相差最少2英寸。如:8寸至少叠10寸，价格按上述价格各层的价格之和计算，标价按照第二层的尺寸。',
      introduce:'六层鲜奶蛋糕',
      url:'https://www.dangao.com/proimgs/709015175228.jpg',
      lun1:'https://www.dangao.com/imgpro/7090154201.jpg',
      img2:'https://www.dangao.com/imgpro/7090154201.jpg',
    },
    {
      cakeid:37,
      name:'红袖添香',
      price:2208,
      oldprice:2308, 
      material:'六层鲜奶蛋糕，鲜奶玫瑰花',
      pack:'恋情,生日,祝福,婚庆,节日,生子',
      word:'新千年结千年缘，百年身伴百年眠；天生才子配佳人，只羡鸳鸯不羡仙。祝你们海枯石烂同心永结，地阔天高比翼齐飞！',
      mark:'六层带支架蛋糕，上下两层的尺寸相差最少2英寸。如:8寸至少叠10寸，价格按上述价格各层的价格之和计算，标价按照第二层的尺寸。',
      introduce:'六层鲜奶蛋糕鲜奶玫瑰',
      url:'https://www.dangao.com/proimgs/709017175228.jpg',
      lun1:'https://www.dangao.com/imgpro/7090174201.jpg',
      img2:'https://www.dangao.com/imgpro/7090174201.jpg',
    },
    {
      cakeid:38,
      name:'勇士之约',
      price:2388,
      oldprice:2408, 
      material:'六层鲜奶水果蛋糕，鲜奶百合花装饰，时令水果。',
      pack:'恋情,生日,祝福,婚庆,生子,',
      word:'天翔比翼鸟，地现连理枝；碧波潭中并蒂莲，鸳鸯嬉水面；宾客连声赞，郎俊新妇贤；百年好合赛神仙，花烛亦展颜。',
      mark:'六层带支架蛋糕，上下两层的尺寸相差最少2英寸。如:8寸至少叠10寸，价格按上述价格各层的价格之和计算，标价按照第二层的尺寸。',
      introduce:'六层鲜奶水果蛋糕',
      url:'https://www.dangao.com/proimgs/709018175228.jpg',
      lun1:'https://www.dangao.com/imgpro/7090184201.jpg',
      img2:'https://www.dangao.com/imgpro/7090184201.jpg',
    },
];

conn.query(`select * from cake`,(err,result)=>{
  if(err){
    console.log(err);
  }else{
    if(result.length == 0){
      for(var i = 0;i < cake.length;i++){
        var c = cake[i];
        conn.query(`insert into cake set ?`,c,(err)=>{
          if(err){
            console.log(err);
            console.log('插入失败');
          }else{
            console.log('插入成功');
          }
        });
      }
    }
  }
});

/* GET home page. */
router.get('/',(req,res)=>{
  var sql = `SELECT *
              FROM classify_cake cc
              LEFT JOIN cake c ON  cc.cakeIid=c.cakeid
              LEFT JOIN classify cl ON cc.classifyId=cl.classifyId`;
  conn.query(sql,(err,result)=>{
    if(err){
      return res.send({
        success:false,
        data:err.message
      });
    }
    return res.send({
      success:true,
      data:result
    });
  });
});

router.get('/type',(req,res)=>{
  conn.query('select * from classify',(err,result)=>{
    if(err){
      return res.send({
        success:false,
        data:err.message
      });
    }
    return res.send({
      success:true,
      data:result
    });
  });
});

router.post('/',(req,res)=>{

  conn.query('select * from cart where cakeid = ? and phone = ?',
    [req.body.cakeid,req.body.phone],
    (err,result)=>{
    console.log(result);
    if(result.length > 0){
      var num = parseInt(new String(result[0].number + 1));
      console.log(num);
      conn.query('update cart set number = ? where cakeid = ? and phone = ?',
        [num,req.body.cakeid,req.body.phone],
        (err,result)=>{
        if(err){
          return res.send({
            success:false,
            data:err.message
          });
        }
        return res.send({
          success:true
        });
      });
    }else{
       conn.query('insert into cart set cakeid = ?,number = ?,phone = ?',
        [req.body.cakeid,req.body.number,req.body.phone],(err,result)=>{
        if(err){
          return res.send({
            success:false,
            data:err.message
          });
        }
        return res.send({
          success:true
        });
      });
    }

  });
 
});

router.get('/cart',(req,res)=>{
  var sql = `SELECT c.url,c.name,c.price,c.number FROM cart ca
            LEFT JOIN cake c ON ca.cakeid = c.cakeid`;
  conn.query(sql,(err,result)=>{
    if(err){
      return res.send({
        success:false,
        data:err.message
      });
    }
    return res.send({
      success:true,
      data:result
    })
  });
})

module.exports = router;
